# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(blank=True, max_length=300, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=300, null=True)),
                ('os', models.CharField(blank=True, max_length=300, null=True)),
                ('os_version', models.CharField(blank=True, max_length=300, null=True)),
                ('device', models.CharField(blank=True, max_length=300, null=True)),
                ('device_brand', models.CharField(blank=True, max_length=300, null=True)),
                ('device_model', models.CharField(blank=True, max_length=300, null=True)),
                ('is_mobile', models.NullBooleanField()),
                ('is_tablet', models.NullBooleanField()),
                ('is_touch_capable', models.NullBooleanField()),
                ('is_pc', models.NullBooleanField()),
                ('is_bot', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shortner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_field', models.CharField(max_length=300)),
                ('shortcode', models.CharField(blank=True, max_length=6, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='analytic',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytic', to='st.Shortner'),
        ),
        migrations.AlterUniqueTogether(
            name='shortner',
            unique_together=set([('user', 'url_field')]),
        ),
    ]
