# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_auto_20171116_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='url',
        ),
        migrations.AddField(
            model_name='shortner',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Analytics',
        ),
    ]
