# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_auto_20171116_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortner',
            name='browser',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shortner',
            name='browser_version',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shortner',
            name='device',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shortner',
            name='device_brand',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shortner',
            name='device_model',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shortner',
            name='is_bot',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='shortner',
            name='is_mobile',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='shortner',
            name='is_pc',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='shortner',
            name='is_tablet',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='shortner',
            name='is_touch_capable',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='shortner',
            name='os',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shortner',
            name='os_version',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
