# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_auto_20171116_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(blank=True, max_length=300, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=300, null=True)),
                ('os', models.CharField(blank=True, max_length=300, null=True)),
                ('os_version', models.CharField(blank=True, max_length=300, null=True)),
                ('device', models.CharField(blank=True, max_length=300, null=True)),
                ('device_brand', models.CharField(blank=True, max_length=300, null=True)),
                ('device_model', models.CharField(blank=True, max_length=300, null=True)),
                ('is_mobile', models.NullBooleanField()),
                ('is_tablet', models.NullBooleanField()),
                ('is_touch_capable', models.NullBooleanField()),
                ('is_pc', models.NullBooleanField()),
                ('is_bot', models.NullBooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='device',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='device_brand',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='is_mobile',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='is_pc',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='is_tablet',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='is_touch_capable',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='os',
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='os_version',
        ),
        migrations.AddField(
            model_name='analytic',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_analytic', to='st.Shortner'),
        ),
    ]
