# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0005_auto_20171116_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytic', to='st.Shortner'),
        ),
    ]
